# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f5a882ac0dee2900e1f7e946d569c8e22a5e6d43d78efe4fab2082456887475862cc335fa2c8739e5d6811fa0ce6efb9be95a1af48664a41b0baae26cdf6818

test:
  secret_key_base: b85297c152fbb11b1ef30a2e038c8f7a3df44a3eb9e113bc82e7b0dab4f0547efef3a8607c84308b5822d1e32dde3c1adccaba069493dc0e6df89c0cecef0e96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
